package com.yztc.lovetv.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yztc.lovetv.bean.BackNeedData;
import com.yztc.lovetv.bean.HistoryBean;
import com.yztc.lovetv.bean.TabItemBean;

import com.yztc.lovetv.greendao.BackNeedDataDao;
import com.yztc.lovetv.greendao.HistoryBeanDao;
import com.yztc.lovetv.greendao.TabItemBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig backNeedDataDaoConfig;
    private final DaoConfig historyBeanDaoConfig;
    private final DaoConfig tabItemBeanDaoConfig;

    private final BackNeedDataDao backNeedDataDao;
    private final HistoryBeanDao historyBeanDao;
    private final TabItemBeanDao tabItemBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        backNeedDataDaoConfig = daoConfigMap.get(BackNeedDataDao.class).clone();
        backNeedDataDaoConfig.initIdentityScope(type);

        historyBeanDaoConfig = daoConfigMap.get(HistoryBeanDao.class).clone();
        historyBeanDaoConfig.initIdentityScope(type);

        tabItemBeanDaoConfig = daoConfigMap.get(TabItemBeanDao.class).clone();
        tabItemBeanDaoConfig.initIdentityScope(type);

        backNeedDataDao = new BackNeedDataDao(backNeedDataDaoConfig, this);
        historyBeanDao = new HistoryBeanDao(historyBeanDaoConfig, this);
        tabItemBeanDao = new TabItemBeanDao(tabItemBeanDaoConfig, this);

        registerDao(BackNeedData.class, backNeedDataDao);
        registerDao(HistoryBean.class, historyBeanDao);
        registerDao(TabItemBean.class, tabItemBeanDao);
    }
    
    public void clear() {
        backNeedDataDaoConfig.clearIdentityScope();
        historyBeanDaoConfig.clearIdentityScope();
        tabItemBeanDaoConfig.clearIdentityScope();
    }

    public BackNeedDataDao getBackNeedDataDao() {
        return backNeedDataDao;
    }

    public HistoryBeanDao getHistoryBeanDao() {
        return historyBeanDao;
    }

    public TabItemBeanDao getTabItemBeanDao() {
        return tabItemBeanDao;
    }

}
